/// Flutter icons Glunote
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Glunote
///      fonts:
///       - asset: fonts/Glunote.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Glunote {
  Glunote._();

  static const _kFontFam = 'Glunote';

  static const IconData glucemia = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData inicio = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData inicio_relleno = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData insulina = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bienestar_d = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mas = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ok = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData perfil_contorno = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData perfil = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData racha = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData registro = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData registro_relleno = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData aprender = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData aprender_relleno = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData bienestar_b = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData bienestar_c = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData comida = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData bienestar = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData ejercicio = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData glunote = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData glunote_marca = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData bienestar_e = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData bienestar_a = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData bienestar_2 = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData flecha_izqicono_glunote = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData flecha_dericono_glunote = const IconData(0xe819, fontFamily: _kFontFam);
}
